name: ric_apps
description: RIC Project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  logger: ^1.3.0
  riverpod: ^2.3.6
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
